#!/usr/bin/env bash
set -euo pipefail

repo_root="$(cd "$(dirname "$0")/.." && pwd)"
env_file="$repo_root/.env"
temp_relay_pid=""
temp_relay_log="$repo_root/install-temp-relay.log"

cleanup_temp_relay() {
  if [ -n "${temp_relay_pid:-}" ] && kill -0 "$temp_relay_pid" >/dev/null 2>&1; then
    kill "$temp_relay_pid" >/dev/null 2>&1 || true
    wait "$temp_relay_pid" >/dev/null 2>&1 || true
  fi
}

trap cleanup_temp_relay EXIT

print_header() {
  printf '\n== %s ==\n' "$1"
}

prompt_default() {
  local var_name="$1"
  local prompt="$2"
  local default_value="$3"
  local value

  if [ -n "$default_value" ]; then
    read -r -p "$prompt [$default_value]: " value
    printf -v "$var_name" '%s' "${value:-$default_value}"
  else
    read -r -p "$prompt: " value
    printf -v "$var_name" '%s' "$value"
  fi
}

prompt_secret() {
  local var_name="$1"
  local prompt="$2"
  local value
  read -r -s -p "$prompt: " value
  printf '\n'
  printf -v "$var_name" '%s' "$value"
}

shell_escape_env() {
  printf "%s" "$1" | sed "s/'/'\\\\''/g; s/^/'/; s/$/'/"
}

write_env() {
  local token="$1"
  local chat_ids="$2"
  local codex_bin="$3"
  local workdir="$4"
  local sandbox="$5"
  local state_dir="$6"
  local extra_path="$7"
  local timeout_sec="$8"

  umask 077
  {
    printf '# Generated by scripts/install.sh\n'
    printf 'TELEGRAM_BOT_TOKEN=%s\n' "$(shell_escape_env "$token")"
    printf 'TELEGRAM_ALLOWED_CHAT_IDS=%s\n' "$(shell_escape_env "$chat_ids")"
    printf 'CODEX_BIN=%s\n' "$(shell_escape_env "$codex_bin")"
    printf 'CODEX_WORKDIR=%s\n' "$(shell_escape_env "$workdir")"
    printf 'CODEX_SANDBOX=%s\n' "$(shell_escape_env "$sandbox")"
    if [ -n "$state_dir" ]; then
      printf 'CODEX_RELAY_STATE_DIR=%s\n' "$(shell_escape_env "$state_dir")"
    fi
    if [ -n "$extra_path" ]; then
      printf 'CODEX_EXTRA_PATH=%s\n' "$(shell_escape_env "$extra_path")"
    fi
    printf 'CODEX_RELAY_TIMEOUT_SEC=%s\n' "$(shell_escape_env "$timeout_sec")"
  } > "$env_file"
  chmod 600 "$env_file"
}

require_command() {
  local command_name="$1"
  if ! command -v "$command_name" >/dev/null 2>&1; then
    printf 'Missing required command: %s\n' "$command_name" >&2
    return 1
  fi
}

print_header "Codex Telegram Bot installer"
printf 'This script creates %s and helps you obtain your Telegram chat_id.\n' "$env_file"
printf 'You will need a Telegram bot token from @BotFather.\n'

print_header "Prerequisite checks"
require_command python3
printf 'python3: %s\n' "$(command -v python3)"

default_codex_bin="$(command -v codex 2>/dev/null || true)"
if [ -z "$default_codex_bin" ]; then
  default_codex_bin="codex"
  printf 'codex was not found on this shell PATH. You can enter an absolute path below.\n'
else
  printf 'codex: %s\n' "$default_codex_bin"
fi

if [ -f "$env_file" ]; then
  printf '\nExisting .env found at %s.\n' "$env_file"
  read -r -p 'Overwrite it? [y/N]: ' overwrite
  case "$overwrite" in
    y|Y|yes|YES) ;;
    *) printf 'Install cancelled.\n'; exit 0 ;;
  esac
fi

print_header "Telegram bot token"
cat <<'INSTRUCTIONS'
In Telegram:
1. Search for @BotFather.
2. Send /newbot.
3. Follow the prompts.
4. Copy the token. It looks like: 123456789:ABCDEF...
INSTRUCTIONS
prompt_secret telegram_token "Paste TELEGRAM_BOT_TOKEN"
if [ -z "$telegram_token" ]; then
  printf 'TELEGRAM_BOT_TOKEN cannot be empty.\n' >&2
  exit 1
fi

print_header "Codex settings"
prompt_default codex_bin "Codex command or absolute path" "$default_codex_bin"
prompt_default workdir "Project directory for new Codex sessions" "$(pwd)"
prompt_default sandbox "Codex sandbox (read-only, workspace-write, danger-full-access)" "workspace-write"
prompt_default timeout_sec "Max seconds per Codex task" "3600"
prompt_default state_dir "Relay state directory, blank for default ~/.codex_telegram_bot" ""
prompt_default extra_path "Extra PATH prefix, blank unless codex/node needs it" ""

if [ ! -d "$workdir" ]; then
  printf 'Project directory does not exist: %s\n' "$workdir" >&2
  exit 1
fi

case "$sandbox" in
  read-only|workspace-write|danger-full-access) ;;
  *)
    printf 'Invalid sandbox: %s\n' "$sandbox" >&2
    printf 'Use one of: read-only, workspace-write, danger-full-access\n' >&2
    exit 1
    ;;
esac

print_header "Temporary relay for chat_id"
write_env "$telegram_token" "" "$codex_bin" "$workdir" "$sandbox" "$state_dir" "$extra_path" "$timeout_sec"
cat <<'INSTRUCTIONS'
The installer will now start the relay temporarily in the background.

In Telegram:
1. Open your new bot chat.
2. Send /id.
3. Copy the chat_id number from the reply.
INSTRUCTIONS

"$repo_root/scripts/start_telegram_codex_relay.sh" > "$temp_relay_log" 2>&1 &
temp_relay_pid=$!
printf 'Temporary relay pid: %s\n' "$temp_relay_pid"
printf 'Temporary relay log: %s\n' "$temp_relay_log"
sleep 1
if ! kill -0 "$temp_relay_pid" >/dev/null 2>&1; then
  printf 'Temporary relay exited early. Log output:\n' >&2
  sed -n '1,120p' "$temp_relay_log" >&2 || true
  exit 1
fi

print_header "Allowlist chat_id"
prompt_default chat_ids "Paste TELEGRAM_ALLOWED_CHAT_IDS (comma-separated if multiple)" ""
if [ -z "$chat_ids" ]; then
  printf 'TELEGRAM_ALLOWED_CHAT_IDS cannot be empty for a usable install.\n' >&2
  exit 1
fi

cleanup_temp_relay
temp_relay_pid=""

write_env "$telegram_token" "$chat_ids" "$codex_bin" "$workdir" "$sandbox" "$state_dir" "$extra_path" "$timeout_sec"
rm -f "$temp_relay_log"

print_header "Done"
printf 'Wrote %s\n' "$env_file"
printf '\nStart the relay with:\n'
printf '  cd %s\n' "$repo_root"
printf '  ./scripts/start_telegram_codex_relay.sh\n'
printf '\nRecommended tmux run:\n'
printf '  tmux new -s codex-telegram\n'
printf '  cd %s\n' "$repo_root"
printf '  ./scripts/start_telegram_codex_relay.sh\n'
printf '\nIn Telegram, send /menu to show the command keyboard.\n'
